# Generated by Django 4.1 on 2023-11-26 11:51

from django.db import migrations

ARTICLES_SAMPLE_DATA = [
    {'title': f'title_{str(i)}', 'content': f'content_{str(i)}'} for i in range(10)
]


def create_sample_articles(apps, schema_editor):
    Article = apps.get_model("article_management", "Article")
    for sample_entry in ARTICLES_SAMPLE_DATA:
        Article.objects.create(
            title=sample_entry['title'],
            content=sample_entry['content']
        )


class Migration(migrations.Migration):
    dependencies = [
        ("article_management", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_sample_articles),
    ]
