# Generated by Django 4.1 on 2023-11-26 14:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article_management", "0003_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="score",
            name="score",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(limit_value=0),
                    django.core.validators.MaxValueValidator(limit_value=5),
                ]
            ),
        ),
    ]
